
// This file was auto-generated by ML.NET Model Builder. 

using MLCostModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLCostModel.ModelInput sampleData = new MLCostModel.ModelInput()
{
    Age = 18F,
    Sex = @"male",
    Bmi = 33.77F,
    Children = 1F,
    Region = @"southeast",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLCostModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Charges with predicted Charges from sample data...\n\n");


Console.WriteLine($"Age: {18F}");
Console.WriteLine($"Sex: {@"male"}");
Console.WriteLine($"Bmi: {33.77F}");
Console.WriteLine($"Children: {1F}");
Console.WriteLine($"Region: {@"southeast"}");
Console.WriteLine($"Charges: {1725.552F}");


Console.WriteLine($"\n\nPredicted Charges: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

